# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9dbb627ace58ec7d5f43e25664c06faab84354f6c9c963abdc933b4f2ea5d8814608dff5878127c785cec38a1a6e6bc24a00ef271bf6157cfacd45b3b307c4c

test:
  secret_key_base: 50a8e31a288c3a4b1c7e0389184c9e0c425be274e63aa733c2d3a284924a990213720895ce3d133125829ee3b7b9c5bc42cc8eb29a77f302a0d33c4c0c0841bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
